/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Siddharth' at '12/31/16 1:59 PM' with Gradle 3.2.1
 *
 * @author Siddharth, @date 12/31/16 1:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
